[project]
name = "adaptive-tsfm-selection"
version = "0.1.0"
description = "Adaptive selection of time-series foundation models using interpretable meta-learning"
requires-python = ">=3.11,<3.12"

dependencies = [
    "numpy>=1.26",
    "pandas>=2.2",
    "scipy>=1.13",
    "statsmodels>=0.14",
    "scikit-learn>=1.5",
    "pyarrow>=17.0",
    "pyyaml>=6.0",
    "matplotlib>=3.9",
    "jupyter>=1.1",
    "ipykernel>=6.29",

    # Deep Learning / tsfm
    "torch>=2.2,<3",
    "chronos-forecasting==2.3.2",
]

[tool.ruff]
line-length = 100

# PyTorch CUDA ------------------------------------
[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'win32' or sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true