datasets:
  ETTh1:
    path: data/raw/ETTh/ETTh1.csv
    domain: energy
    timestamp_column: date
    primary_target: OT
    expected_frequency: 1h
    seasonal_period: 24

  Weather:
    path: data/raw/weather/weather.csv
    domain: weather
    timestamp_column: date
    primary_target: null
    expected_frequency: 10min
    seasonal_period: 144

  Electricity:
    path: data/raw/electricity/electricity.csv
    domain: energy
    timestamp_column: date
    primary_target: null
    expected_frequency: 1h
    seasonal_period: 24

  Traffic:
    path: data/raw/traffic/traffic.csv
    domain: transportation
    timestamp_column: date
    primary_target: null
    expected_frequency: 1h
    seasonal_period: 24

  Exchange:
    path: data/raw/exchange/exchange_rate.csv
    domain: finance
    timestamp_column: date
    primary_target: null
    expected_frequency: 1d
    seasonal_period: 1

  Solar:
    path: data/raw/solar/solar.csv
    domain: renewable_energy
    timestamp_column: null
    start_time: "2006-01-01 00:00:00"
    primary_target: null
    expected_frequency: 10min
    seasonal_period: 144
